TechStoreApp/Models/Components/SessionItemViewModel.cs
using TechStoreApp.Infrastructure.Data.EnumTypes;

namespace TechStoreApp.Models.Components;

public class SessionItemViewModel
{
	public Guid ProductId { get; set; }

	public string Name { get; set; } = null!;

	public string Price { get; set; } = null!;

	public string PriceForAll { get; set; } = null!;

	public string Slug { get; set; } = null!;

	public string ImageUrl { get; set; } = null!;

	public int Quantity { get; set; }

	public SessionStatus Status { get; set; }
}

TechStoreApp/Models/Components/SessionViewModel.cs
using TechStoreApp.Infrastructure.Data.EnumTypes;

namespace TechStoreApp.Models.Components;

public class SessionViewModel
{
	public SessionStatus Status { get; set; }
	public List<SessionItemViewModel> Items { get; set; } = [];
	public string TotalPrice { get; set; }
}

TechStoreApp/Controllers/SessionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Mvc;
using TechStoreApp.Contracts;
using TechStoreApp.Core.Contracts;
using TechStoreApp.Core.Models.Params;
using TechStoreApp.Core.Models.Params.Wishlist;
using TechStoreApp.Infrastructure.Data.EnumTypes;
using TechStoreApp.Models.Pages;

namespace TechStoreApp.Controllers;

[Authorize]
public class SessionController : BaseController
{
	private readonly ISessionService _sessionService;
	private readonly IOrderService _orderService;
	private readonly IUIService _uiService;

	public SessionController(
		ISessionService sessionService,
		IUIService uiService,
		IAccountService accountService,
		IOrderService orderService)
		: base(accountService)
	{
		this._sessionService = sessionService;
		this._uiService = uiService;
		this._orderService = orderService;
	}

	[HttpGet]
	public async Task<IActionResult> Index(
		SessionStatus status)
	{
		var breadcrumb = this._uiService.CreateSessionBreadcrumb(status);

		var viewModel = new SessionIndexPageViewModel()
		{
			Breadcrumb = breadcrumb,
			Status = status,
		};

		return this.View(nameof(Index), viewModel);
	}

	[HttpGet]
	[Route("cart/checkout")]
	public async Task<IActionResult> Checkout()
	{
		var count = await this._sessionService.Count(this.CurrentUserId, SessionStatus.InCart);
		if (count <= 0)
		{
			return this.BadRequest();
		};

		return this.View();
	}

	[HttpPost]
	[Route("cart/checkout")]
	public async Task<IActionResult> Checkout(
		OrderParams orderParams)
	{
		if (!this.ModelState.IsValid)
		{
			return this.View();
		}

		var count = await this._sessionService.Count(this.CurrentUserId, SessionStatus.InCart);
		if (count <= 0)
		{
			return this.BadRequest();
		};

		await this._orderService.Create(orderParams, this.CurrentUserId);

		return this.RedirectToAction("Index", "Products");
	}

	[HttpGet]
	[Route("cart")]
	public async Task<IActionResult> Cart()
	{
		return await this.Index(status: SessionStatus.InCart);
	}

	[HttpGet]
	[Route("wishlist")]
	public async Task<IActionResult> Wishlist()
	{
		return await this.Index(status: SessionStatus.Wishlisted);
	}

	[HttpPost]
	[EnableCors("AllowSpecificOrigins")]
	public async Task<IActionResult> ChangeStatus(
		SessionChangeStatusParams reqParams)
	{
		if (!this.ModelState.IsValid)
		{
			return this.BadRequest();
		}

		var isDeleted = await this._sessionService
			.ChangeStatus(this.CurrentUserId, reqParams.ProductId, reqParams.Status);

		object jsonData = new
		{
			status = StatusCodes.Status200OK,
			isDeleted
		};

		return this.Json(jsonData);
	}

	[HttpPost]
	[EnableCors("AllowSpecificOrigins")]
	public async Task<IActionResult> ChangeQuantity(
		SessionChangeQuantityParams reqParams)
	{
		if (!this.ModelState.IsValid)
		{
			return this.BadRequest();
		}

		bool isUpdated = await this._sessionService
			.EditQuantity(reqParams.ProductId, this.CurrentUserId, reqParams.Status, reqParams.NewQuantity);

		object jsonData = new
		{
			status = StatusCodes.Status200OK,
			isUpdated
		};

		return this.Json(jsonData);
	}
}

TechStoreApp/Views/Session/Index/Index.cshtml
@using TechStoreApp.Infrastructure.Data.EnumTypes
@using TechStoreApp.Models.Pages
@model SessionIndexPageViewModel;

<partial name="_Breadcrumb" model="Model.Breadcrumb" />

<vc:session status="@Model.Status"></vc:session>

TechStoreApp/Views/Session/Index/Session.cshtml
@using TechStoreApp.Infrastructure.Data.EnumTypes
@model SessionViewModel

<section class="tp-cart-area pb-120">
    <div class="container">
        <div class="row">
            @{
                var layoutClass = Model.Status == SessionStatus.InCart && Model.Items.Count > 0
                ? "col-xl-9 col-lg-8 "
                : "col-xxl-12";
            }
            <div class="@layoutClass" id="cartProductList">
                <div class="tp-cart-list mb-45 mr-30">
                    <table class="table">
                        <thead>
                            <tr>
                                <th style="min-width: 150px;" class="tp-cart-header-product">Product</th>
                                <th class="tp-cart-header-product">Name</th>
                                <th class="tp-cart-header-price">Price</th>
                                <th class="tp-cart-header-quantity">Quantity</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Items)
                            {
                                <partial name="Index/_SessionItem" model="item" />
                            }
                        </tbody>
                    </table>
                </div>
                <div class="tp-cart-bottom">
                    <div class="row align-items-end">
                        <div class="col-xl-6 col-md-4">
                            <div class="tp-cart-update">
                                @if (Model.Status == SessionStatus.Wishlisted)
                                {
                                    <a asp-action="Cart" asp-controller="Session" class="tp-cart-update-btn">Go To Cart</a>
                                }
                                else
                                {
                                    <a asp-action="Index" asp-controller="Products" class="tp-cart-update-btn">Go To Shop</a>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            @if (Model.Status == SessionStatus.InCart && Model.Items.Count > 0)
            {
                <div class="col-xl-3 col-lg-4" id="checkoutCard">
                    <div class="tp-cart-checkout-wrapper">
                        <div class="tp-cart-checkout-top d-flex align-items-center justify-content-between">
                            <span class="tp-cart-checkout-top-title">Subtotal</span>
                            <span class="tp-cart-checkout-top-price total-checkout-price">@Model.TotalPrice</span>
                        </div>
                        <div class="tp-cart-checkout-shipping row">
                            <div class="col-6">
                                Free Shipping
                            </div>
                            <div class="col-6 text-end">
                                $0.00
                            </div>
                        </div>
                        <div class="tp-cart-checkout-total d-flex align-items-center justify-content-between">
                            <span>Total</span>
                            <span class="total-checkout-price">@Model.TotalPrice</span>
                        </div>
                        <div class="tp-cart-checkout-proceed">
                            <a href="/cart/checkout" class="tp-cart-checkout-btn w-100">Proceed to Checkout</a>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>

<script type="module" src="~/js/pages/session.js"></script>

TechStoreApp/Views/Session/Index/_SessionItem.cshtml
@model SessionItemViewModel

<tr class="session-item" data-product-id="@Model.ProductId">
    <td class="tp-cart-img">
        <a href=@($"/products/details/{Model.Slug}")>
            <img src="@Model.ImageUrl" alt="">
        </a>
    </td>

    <td class="tp-cart-title">
        <a href=@($"/products/details/{Model.Slug}")>@Model.Name</a>
    </td>

    <td class="tp-cart-price">
        <span class="session-price" data-product-id="@Model.ProductId">@Model.PriceForAll</span>
    </td>

    <td class="tp-cart-quantity">
        <div class="tp-product-quantity mt-10 mb-10">
            <span class="tp-cart-minus">
                <svg width="10" height="2" viewBox="0 0 10 2" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M1 1H9" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                </svg>
            </span>
            <input
                class="tp-cart-input session-quantity"
                type="text"
                data-product-id="@Model.ProductId"
                data-status="@Model.Status"
                data-showed-price="@Model.Price"
                value="@Model.Quantity">
            <span class="tp-cart-plus">
                <svg width="10" height="10" viewBox="0 0 10 10" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M5 1V9" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                    <path d="M1 5H9" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                </svg>
            </span>
        </div>
    </td>

    <td class="tp-cart-action">
        <form class="session-remove-form" data-product-id="@Model.ProductId" data-status="@Model.Status">
            <button type="submit" class="tp-cart-action-btn">
                <svg width="10" height="10" viewBox="0 0 10 10" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" clip-rule="evenodd" d="M9.53033 1.53033C9.82322 1.23744 9.82322 0.762563 9.53033 0.46967C9.23744 0.176777 8.76256 0.176777 8.46967 0.46967L5 3.93934L1.53033 0.46967C1.23744 0.176777 0.762563 0.176777 0.46967 0.46967C0.176777 0.762563 0.176777 1.23744 0.46967 1.53033L3.93934 5L0.46967 8.46967C0.176777 8.76256 0.176777 9.23744 0.46967 9.53033C0.762563 9.82322 1.23744 9.82322 1.53033 9.53033L5 6.06066L8.46967 9.53033C8.76256 9.82322 9.23744 9.82322 9.53033 9.53033C9.82322 9.23744 9.82322 8.76256 9.53033 8.46967L6.06066 5L9.53033 1.53033Z" fill="currentColor" />
                </svg>
                <span>Remove</span>
            </button>
        </form>
    </td>
</tr>